ENG-10087: Add two functions get_token and download_sidecar to download sidecar.compose.yaml into an Azure virtual machine instance

diff --git a/files/cloud-init-azure.sh.tmpl b/files/cloud-init-azure.sh.tmpl
--- a/files/cloud-init-azure.sh.tmpl
+++ b/files/cloud-init-azure.sh.tmpl
@@ -7,6 +7,25 @@ echo \
 sudo apt-get update -y
 sudo apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin -y
 
+function retry() {
+  RETRIES=15
+  while [ $RETRIES -gt 0 ]; do
+    set +e
+    $@
+    RESULT=$?
+    set -e
+    if [ $RESULT -eq 0 ]; then
+      echo "Success"
+      return 0
+    fi
+    echo "Failed"
+    sleep 5
+    let RETRIES-=1
+  done
+  echo "Retries exceeded"
+  exit 3
+}
+
 export PUBLIC_REPO=artifacts.cyralpublic.appspot.com
 export GCS_API_ENDPOINT=https://storage.googleapis.com
 export DOCKER_COMPOSE_VERSION=1.29.2
@@ -93,31 +112,44 @@ az login --identity
 SIDECAR_CLIENT_ID=$(az keyvault secret show --vault-name cyral-sidecar-key --name cyral-sidecars-2GSU5allmcQUGR76xd4LB2nRGTm-self-signed-certificate --query value -o tsv | jq -r .clientId)
 SIDECAR_CLIENT_SECRET=$(az keyvault secret show --vault-name cyral-sidecar-key --name cyral-sidecars-2GSU5allmcQUGR76xd4LB2nRGTm-self-signed-certificate --query value -o tsv | jq -r .clientSecret)
 
-# echo "Downloading sidecar.compose.yaml..."
-# function get_token () {
-#   local url_token="${protocol}://${controlplane_host}:$1/v1/users/oidc/token"
-#   token=$(${curl} --fail --no-progress-meter --request POST "$url_token" -d grant_type=client_credentials -d client_id="$${SIDECAR_CLIENT_ID}" -d client_secret="$${SIDECAR_CLIENT_SECRET}" 2>&1)
-#   token_error=$(echo $?)
-# }
+echo "Downloading sidecar.compose.yaml..."
+echo "protocol: ${protocol}"
+echo "controlaplane_host: ${controlplane_host}"
+echo "curl: ${curl}"
+echo "SIDECAR_CLIENT_ID: $SIDECAR_CLIENT_ID"
+echo "SIDECAR_CLIENT_SECRET: $SIDECAR_CLIENT_SECRET"
+echo "sidecar_version: ${sidecar_version}"
 
-# function download_sidecar () {
-#   # Test default (443) and then 8000
-#   get_token "443"
-#   if [[ $token_error -ne 0 ]]; then
-#     get_token "8000"
-#     if [[ $token_error -ne 0 ]]; then
-#       return 1
-#     fi
-#   fi
-#   local access_token=$(echo "$token" | jq -r .access_token)
-#   local url="${protocol}://${controlplane_host}/deploy/docker-compose?TemplateVersion=${sidecar_version}&TemplateType=terraform&LogIntegration=${log_integration}&MetricsIntegration=${metrics_integration}&HCVaultIntegrationID=${hc_vault_integration_id}&WiresEnabled=${repositories_supported}"
-#   echo "Trying to download the sidecar template from: $url"
-#   if [[ $(${curl} -s -o /home/ec2-user/sidecar.compose.yaml -w "%%{http_code}" -L "$url" -H "Authorization: Bearer $access_token") = 200 ]]; then
-#     return 0
-#   fi
-#   return 1
-# }
-# retry download_sidecar
+function get_token() {
+  local url_token="${protocol}://${controlplane_host}:$1/v1/users/oidc/token"
+  token=$(${curl} --fail --no-progress-meter --request POST "$url_token" -d grant_type=client_credentials -d client_id="$${SIDECAR_CLIENT_ID}" -d client_secret="$${SIDECAR_CLIENT_SECRET}" 2>&1)
+  token_error=$(echo $?)
+}
+
+function download_sidecar() {
+  echo "Executing download_sidecar function..."
+  # Test default (443) and then 8000
+  get_token "443"
+  if [[ $token_error -ne 0 ]]; then
+    get_token "8000"
+    if [[ $token_error -ne 0 ]]; then
+      return 1
+    fi
+  fi
+  local access_token=$(echo "$token" | jq -r .access_token)
+  local url="${protocol}://${controlplane_host}/deploy/docker-compose?TemplateVersion=${sidecar_version}&TemplateType=terraform&LogIntegration=${log_integration}&MetricsIntegration=${metrics_integration}&HCVaultIntegrationID=${hc_vault_integration_id}&WiresEnabled=${repositories_supported}"
+  echo "Trying to download the sidecar template from: $url"
+  if [[ $(${curl} -s -o /home/adminuser/sidecar.compose.yaml -w "%%{http_code}" -L "$url" -H "Authorization: Bearer $access_token") = 200 ]]; then
+    return 0
+  fi
+  return 1
+}
+
+declare -f get_token
+declare -f download_sidecar
+
+retry download_sidecar
 
 unset SIDECAR_CLIENT_ID
 unset SIDECAR_CLIENT_SECRET
+
